(function(q,z,r){if("object"===typeof r&&"string"!==typeof r.nodeName)z(q,r);else{var x=function(d){for(var k in d)d.hasOwnProperty(k)&&(d[k]=x(d[k]));return Object.freeze(d)};r={};z(q,r);for(var u in r)!r.hasOwnProperty(u)||null!=Object.getOwnPropertyDescriptor(q,u)&&null!=Object.getOwnPropertyDescriptor(q[u],"1.2.6-iab634")||(null==Object.getOwnPropertyDescriptor(q,u)&&Object.defineProperty(q,u,{value:{}}),Object.defineProperty(q[u],"1.2.6-iab634",{get:function(){return x(r[u])},enumerable:!0}))}})("undefined"===
typeof global?this:global,function(q,z){function r(a,b){return a&&(a[b]||(a[b]={}))}function x(a,b){"undefined"!==typeof jasmine&&jasmine?a():"undefined"!==typeof console&&console&&console.error&&b()}function u(a,b){return b.reduce(function(a,b){return a&&a[b]},a)}var d=d||{};d.scope={};d.inherits=function(a,b){function t(){}t.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new t;a.prototype.constructor=a;for(var c in b)if("prototype"!=c)if(Object.defineProperties){var g=Object.getOwnPropertyDescriptor(b,
c);g&&Object.defineProperty(a,c,g)}else a[c]=b[c]};d.ASSUME_ES5=!1;d.ASSUME_NO_NATIVE_MAP=!1;d.ASSUME_NO_NATIVE_SET=!1;d.defineProperty=d.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};d.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};d.global=d.getGlobal(this);d.SYMBOL_PREFIX="jscomp_symbol_";d.initSymbol=function(){d.initSymbol=
function(){};d.global.Symbol||(d.global.Symbol=d.Symbol)};d.symbolCounter_=0;d.Symbol=function(a){return d.SYMBOL_PREFIX+(a||"")+d.symbolCounter_++};d.initSymbolIterator=function(){d.initSymbol();var a=d.global.Symbol.iterator;a||(a=d.global.Symbol.iterator=d.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&d.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return d.arrayIterator(this)}});d.initSymbolIterator=function(){}};d.arrayIterator=function(a){var b=
0;return d.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};d.iteratorPrototype=function(a){d.initSymbolIterator();a={next:a};a[d.global.Symbol.iterator]=function(){return this};return a};d.makeIterator=function(a){d.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):d.arrayIterator(a)};d.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};d.arrayFromIterable=function(a){return a instanceof Array?a:d.arrayFromIterator(d.makeIterator(a))};
var k={assertTruthyString:function(a,b){if(!b)throw Error("Value for "+a+" is undefined, null or blank.");if("string"!==typeof b&&!(b instanceof String))throw Error("Value for "+a+" is not a string.");if(""===b.trim())throw Error("Value for "+a+" is empty string.");},assertNotNullObject:function(a,b){if(null==b)throw Error("Value for "+a+" is undefined or null");},assertNumber:function(a,b){if(null==b)throw Error(a+" must not be null or undefined.");if("number"!==typeof b||isNaN(b))throw Error("Value for "+
a+" is not a number");},assertNumberBetween:function(a,b,c,e){(0,k.assertNumber)(a,b);if(b<c||b>e)throw Error("Value for "+a+" is outside the range ["+c+","+e+"]");},assertFunction:function(a,b){if(!b)throw Error(a+" must not be truthy.");},assertPositiveNumber:function(a,b){(0,k.assertNumber)(a,b);if(0>b)throw Error(a+" must be a positive number.");}};var E=function(a){return/\d+\.\d+\.\d+(-.*)?/.test(a)};var C=function(a,b){a=a.split("-")[0].split(".");b=b.split("-")[0].split(".");for(var c=0;3>
c;c++){var e=parseInt(a[c],10),g=parseInt(b[c],10);if(e>g)break;else if(e<g)return!1}return!0};var v=function(a,b){return(0,E)(a)&&(0,C)(a,"1.0.3")?b:JSON.stringify(b)};var F=function(a,b){return(0,E)(a)&&(0,C)(a,"1.0.3")?b?b:[]:b&&"string"===typeof b?JSON.parse(b):[]};var n=function(a,b,c,e){this.guid=a;this.method=b;this.version=c;this.args=e};n.isValidSerializedMessage=function(a){return!!a&&void 0!==a.omid_message_guid&&void 0!==a.omid_message_method&&void 0!==a.omid_message_version&&"string"===
typeof a.omid_message_guid&&"string"===typeof a.omid_message_method&&"string"===typeof a.omid_message_version&&(void 0===a.omid_message_args||void 0!==a.omid_message_args)};n.deserialize=function(a){return new n(a.omid_message_guid,a.omid_message_method,a.omid_message_version,a.omid_message_args)};n.prototype.serialize=function(){var a={};a=(a.omid_message_guid=this.guid,a.omid_message_method=this.method,a.omid_message_version=this.version,a);void 0!==this.args&&(a.omid_message_args=this.args);return a};
var l=function(a){this.to=a;this.communicationType_="NONE"};l.prototype.sendMessage=function(a,b){};l.prototype.handleMessage=function(a,b){if(this.onMessage)this.onMessage(a,b)};l.prototype.generateGuid=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return a="y"===a?(b&3|8).toString(16):b.toString(16)})};l.prototype.serialize=function(a){return JSON.stringify(a)};l.prototype.deserialize=function(a){return JSON.parse(a)};l.prototype.isDirectCommunication=
function(){return"DIRECT"===this.communicationType_};var h={OMID_PRESENT_FRAME_NAME:"omid_v1_present",isOmidPresent:function(a){try{return a.frames?!!a.frames[h.OMID_PRESENT_FRAME_NAME]:!1}catch(b){return!1}},declareOmidPresence:function(a){a.frames&&a.document&&(h.OMID_PRESENT_FRAME_NAME in a.frames||(null==a.document.body&&h.isMutationObserverAvailable_(a)?h.registerMutationObserver_(a):a.document.body?h.appendPresenceIframe_(a):a.document.write('<iframe style="display:none" '+('id="'+h.OMID_PRESENT_FRAME_NAME+
'"')+(' name="'+h.OMID_PRESENT_FRAME_NAME+'">')+"</iframe>")))},appendPresenceIframe_:function(a){var b=a.document.createElement("iframe");b.id=h.OMID_PRESENT_FRAME_NAME;b.name=h.OMID_PRESENT_FRAME_NAME;b.style.display="none";a.document.body.appendChild(b)},isMutationObserverAvailable_:function(a){return"MutationObserver"in a},registerMutationObserver_:function(a){var b=new MutationObserver(function(c){c.forEach(function(c){"BODY"===c.addedNodes[0].nodeName&&(h.appendPresenceIframe_(a),b.disconnect())})});
b.observe(a.document.documentElement,{childList:!0})}},p=function(a){l.call(this,a);this.communicationType_="DIRECT";this.handleExportedMessage=p.prototype.handleExportedMessage.bind(this)};d.inherits(p,l);p.prototype.sendMessage=function(a,b){b=void 0===b?this.to:b;if(!b)throw Error("Message destination must be defined at construction time or when sending the message.");b.handleExportedMessage(a.serialize(),this)};p.prototype.handleExportedMessage=function(a,b){n.isValidSerializedMessage(a)&&this.handleMessage(n.deserialize(a),
b)};var B={error:function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];x(function(){throw new (Function.prototype.bind.apply(Error,[null].concat(["Could not complete the test successfully - "],d.arrayFromIterable(b))));},function(){return console.error.apply(console,[].concat(d.arrayFromIterable(b)))})},debug:function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];x(function(){},function(){return console.error.apply(console,[].concat(d.arrayFromIterable(b)))})}},
w=eval("this");var m=function(){if("undefined"!==typeof q&&q)return q;if("undefined"!==typeof global&&global)return global;if("undefined"!==typeof window&&window)return window;if("undefined"!==typeof w&&w)return w;throw Error("Could not determine global object context.");}();var y=function(a,b){b=void 0===b?m:b;l.call(this,b);var c=this;this.communicationType_="POST_MESSAGE";a.addEventListener("message",function(a){if("object"===typeof a.data){var b=a.data;n.isValidSerializedMessage(b)&&(b=n.deserialize(b),
a.source&&c.handleMessage(b,a.source))}})};d.inherits(y,l);y.isCompatibleContext=function(a){return!!(a&&a.addEventListener&&a.postMessage)};y.prototype.sendMessage=function(a,b){b=void 0===b?this.to:b;if(!b)throw Error("Message destination must be defined at construction time or when sending the message.");b.postMessage(a.serialize(),"*")};var A=function(a){"undefined"===typeof a&&"undefined"!==typeof window&&window&&(a=window);if("undefined"===typeof a||!a||"undefined"===typeof a.top||!a.top)return m;
if(a===a.top)return a;try{return"undefined"===typeof a.top.location.hostname?a:a.top}catch(b){return a}};var f=function(a,b,c){c=void 0===c?h.isOmidPresent:c;return(b=u(a,b))?new p(b):a.top&&c(a.top)?new y(a,a.top):null};var c=function(a){if(this.communication=void 0===a?(0,f)((0,A)(),["omid","v1_VerificationServiceCommunication"]):a)this.communication.onMessage=this.handleMessage_.bind(this);else if(a=(a=m.omid3p)&&"function"===typeof a.registerSessionObserver&&"function"===typeof a.addEventListener?
a:null)this.omid3p=a;this.remoteIntervals_=this.remoteTimeouts_=0;this.callbackMap_={};this.imgCache_=[]};c.prototype.isSupported=function(){return!!this.communication};c.prototype.registerSessionObserver=function(a,b){(0,k.assertFunction)("functionToExecute",a);this.omid3p?this.omid3p.registerSessionObserver(a,b):this.sendMessage_("addSessionListener",a,b)};c.prototype.addEventListener=function(a,b){(0,k.assertTruthyString)("eventType",a);(0,k.assertFunction)("functionToExecute",b);this.omid3p?this.omid3p.addEventListener(a,
b):this.sendMessage_("addEventListener",b,a)};c.prototype.sendUrl=function(a,b,c){(0,k.assertTruthyString)("url",a);m.document&&m.document.createElement?this.sendUrlWithImg_(a,b,c):this.sendMessage_("sendUrl",function(a){a&&b?b():!a&&c&&c()},a)};c.prototype.sendUrlWithImg_=function(a,b,c){var e=this,t=m.document.createElement("img");this.imgCache_.push(t);var d=function(a){var b=e.imgCache_.indexOf(t);0<=b&&e.imgCache_.splice(b,1);a&&a()};t.addEventListener("load",d.bind(this,b));t.addEventListener("error",
d.bind(this,c));t.src=a};c.prototype.injectJavaScriptResource=function(a,b,c){var e=this;(0,k.assertTruthyString)("url",a);m.document?this.injectJavascriptResourceUrlInDom_(a,b,c):this.sendMessage_("injectJavaScriptResource",function(t,d){t?(e.evaluateJavaScript_(d,a),b()):(B.error("Service failed to load JavaScript resource."),c())},a)};c.prototype.injectJavascriptResourceUrlInDom_=function(a,b,c){var e=m.document,t=e.body;e=e.createElement("script");e.onload=b;e.onerror=c;e.src=a;e.type="application/javascript";
t.appendChild(e)};c.prototype.evaluateJavaScript_=function(a,b){try{eval(a)}catch(t){B.error('Error evaluating the JavaScript resource from "'+b+'".')}};c.prototype.setTimeout=function(a,b){(0,k.assertFunction)("functionToExecute",a);(0,k.assertPositiveNumber)("timeInMillis",b);if(this.hasTimeoutMethods_())return m.setTimeout(a,b);var c=this.remoteTimeouts_++;this.sendMessage_("setTimeout",a,c,b);return c};c.prototype.clearTimeout=function(a){(0,k.assertPositiveNumber)("timeoutId",a);this.hasTimeoutMethods_()?
m.clearTimeout(a):this.sendOneWayMessage_("clearTimeout",a)};c.prototype.setInterval=function(a,b){(0,k.assertFunction)("functionToExecute",a);(0,k.assertPositiveNumber)("timeInMillis",b);if(this.hasIntervalMethods_())return m.setInterval(a,b);var c=this.remoteIntervals_++;this.sendMessage_("setInterval",a,c,b);return c};c.prototype.clearInterval=function(a){(0,k.assertPositiveNumber)("intervalId",a);this.hasIntervalMethods_()?m.clearInterval(a):this.sendOneWayMessage_("clearInterval",a)};c.prototype.hasTimeoutMethods_=
function(){return"function"===typeof m.setTimeout&&"function"===typeof m.clearTimeout};c.prototype.hasIntervalMethods_=function(){return"function"===typeof m.setInterval&&"function"===typeof m.clearInterval};c.prototype.handleMessage_=function(a,b){b=a.method;var c=a.guid;a=a.args;if("response"===b&&this.callbackMap_[c]){var e=(0,F)("1.2.6-iab634",a);this.callbackMap_[c].apply(this,e)}"error"===b&&window.console&&B.error(a)};c.prototype.sendOneWayMessage_=function(a,b){for(var c=[],e=1;e<arguments.length;++e)c[e-
1]=arguments[e];this.sendMessage_.apply(this,[].concat([a,null],d.arrayFromIterable(c)))};c.prototype.sendMessage_=function(a,b,c){for(var e=[],d=2;d<arguments.length;++d)e[d-2]=arguments[d];this.communication&&(d=this.communication.generateGuid(),b&&(this.callbackMap_[d]=b),e=new n(d,"VerificationService."+a,"1.2.6-iab634",(0,v)("1.2.6-iab634",e)),this.communication.sendMessage(e))};(0,function(a,b,c){if(c=void 0===c?"undefined"===typeof z?null:z:c)a=a.split("."),a.slice(0,a.length-1).reduce(r,c)[a[a.length-
1]]=b})("OmidVerificationClient",c)},"undefined"===typeof exports?void 0:exports);
(function(){function q(){var c={location:{protocol:"https:"}};c.parent=c;c.top=c;c.document={getElementById:function(){},createElement:function(){},body:{insertBefore:function(){}},querySelectorAll:function(){return[]}};return c}function z(c,a){var b=f.getReportUrl(f.ErrorTypes.LoadTagError,"failedToLoadDVM",!0),d="window.tagUniqueKey = "+h,e=u(c);a='<html><head><script type="text/javascript">'+d+';\x3c/script><script type="text/javascript">('+function(){window.$dv=window.parent.$dv;window.$dv.isFrameSupported=
!0;window.$frmId=Math.random().toString(36)+Math.random().toString(36);window.dv_flow=2}.toString()+')();\x3c/script></head><body><script type="text/javascript">('+function(a,b){if(a){var c=document.createElement("script");c.src=a;c.onerror=function(){(new Image(1,1)).src=b};document.body.appendChild(c)}}.toString()+')("'+a+'", "'+b+'");\x3c/script></body></html>';e?(e.open(),e.write(a),e.close()):(e=encodeURIComponent(a.replace(/'/g,"\\'").replace(/\n|\r\n|\r/g,"")),c.src='javascript: (function(){document.open();document.domain="'+
window.document.domain+"\";document.write('"+e+"');})()")}function r(c){var a=Math.floor(1E12*(Math.random()+"")),b=document.createElement("iframe");b.name=b.id="iframe_"+a;b.setAttribute("data-dv-frm",a);b.width="0";b.height="0";b.style.display="none";b.src=c;return b}function x(c){if(document.currentScript)document.currentScript.parentNode.insertBefore(c,document.currentScript);else if(document.body)document.body.insertBefore(c,document.body.firstChild);else{var a=document.getElementsByTagName("head")[0];
a.insertBefore(c,a.firstChild)}}function u(c){return c&&(c.contentDocument||c.contentWindow&&c.contentWindow.document||frames&&frames[c.name]&&frames[c.name].document)}function d(c){var a=r("about:blank");x(a);z(a,c)}function k(c){try{(new Image(1,1)).src=c}catch(a){}}function E(c,a,b){var d=window.document,e=d.body;d=d.createElement("script");d.onload=a;d.onerror=b;d.src=c;d.type="application/javascript";e.appendChild(d);$dv.tagData[h].isSibling=1}function C(c,a,b){a=a||function(){};b=b||function(){};
$frmId=Math.random().toString(36)+Math.random().toString(36);if(p){var d=f.ErrorTypes.OmidLoadTagError,e=f.ErrorTypes.OmidNativeCollectData;if("object"===typeof omidNative&&"function"===typeof omidNative.downloadJavaScriptResource){var g=f.getReportUrl(e,"ONStartDownload",!1);v(g);omidNative.downloadJavaScriptResource(c,function(c){g=f.getReportUrl(e,"ONDownloadSuccess",!1);v(g);try{eval(c),a()}catch(G){b(G),g=f.getReportUrl(d,"FailedToEval__"+G.message,!0),v(g)}},function(){g=f.getReportUrl(d,"FailedToDownload",
!0);v(g)})}else g=f.getReportUrl(d,"omidNativeNotFound",!0),v(g)}else E(c,a,b)}function v(c,a,b){a=a||function(){};b=b||function(){};if(p){if("object"===typeof omidNative&&"function"===typeof omidNative.sendUrl)return omidNative.sendUrl(c,a,b)}else{var d=new Image(1,1);d.onerror=b;d.onload=a;d.src=c}}function F(c,a,b){c||(c={message:"error undefined"});c=["https://tps.doubleverify.com/visit.jpg?ctx=818052&cmp=1619415&dvtagver=6.1.src&dvp_isLostImp=",b,"&dvp_jsErrMsg=",c.message,"&napr=",c.message,
"&cerrt=",a,"&tgjsver=501"].join("");p&&(c+="&dvp_idle=1");w.isSupported()&&(c+="&dvp_iomd=1");n&&(c=c+"&dvp_csp=1"+("&dvp_csplog="+l));c=encodeURI(c);w.isSupported()?w.report(c):k(c)}dv_flow=2;var n=!1,l=0;try{var h=Math.floor((1-Math.random())*Date.now())}catch(c){h=0}var p=!1;"undefined"===typeof window&&(p=!0);if(!p)try{(function(){try{try{var c=r("about:blank")}catch(a){l|=64;return}try{x(c)}catch(a){l|=1;return}n=!u(c)}catch(a){n=!0,l|=2,"function"===typeof c.remove&&c.remove()}})()}catch(c){}var B=
function(){var c;return{getMeasurementsScriptUrl:function(a){if(!c){var b=[{src:"dv-measurements"}];c=b&&b[0]}return c&&[a,"//cdn.doubleverify.com/",c.src,"501.js"].join("")}}}(),w={omidObject:null,isOmidSupported:null,report:v,isSupported:function(){if(null!==this.isOmidSupported&&void 0!==this.isOmidSupported)return this.isOmidSupported;try{this.omidObject||(this.omidObject=new OmidVerificationClient["1.2.6-iab634"]),this.isOmidSupported=this.omidObject.isSupported()}catch(a){if(this.isOmidSupported=
!1,f){var c=f.getReportUrl(f.ErrorTypes.OmidUnexpectedError,"isSupported__"+a.message,!1);this.report(c)}}return this.isOmidSupported},getVendorKey:function(){if(!p&&A){var c=(c=A.getQueryStringParams())&&c.vendor_key;window.$dv.omidVendorKeyExtracted=Number(!!c)}return c||"doubleverify.com-omid"},execute:function(){var c=this,a=this.omidObject,b=this.getVendorKey();$dv.omidJsClient=a;$dv.omidVendorKey=b;($dv.isDomlessEnvironment=p)&&(window=q());a.registerSessionObserver(function(a){try{switch(a.type){case "sessionStart":$dv.omidSessionData=
a;$dv.omidAccessMode=a&&a.data&&a.data.context&&a.data.context.accessMode;try{$dv.omidSessionStartTime=Date.now?Date.now():(new Date).getTime()}catch(D){var b=f.getReportUrl(f.ErrorTypes.OmidUnexpectedError,"Date.now__"+D.message,!1);v(b)}var g=B.getMeasurementsScriptUrl("https:");if(p)C(g);else try{d(g)}catch(D){l|=128,b=f.getReportUrl(f.ErrorTypes.OmidUnexpectedError,"injectScriptSteps__"+D.message,!1),v(b),window.tagUniqueKey=h,C(g)}break;case "sessionError":b=f.getReportUrl(f.ErrorTypes.OmidSessionError,
a.data&&a.data.message||"",!0),c.report(b)}}catch(D){a=f.getReportUrl(f.ErrorTypes.OmidUnexpectedLostImpError,"omidCallback__"+D.message,!0),v(a)}},b)}},m={execute:function(){try{var c=document.currentScript&&0==document.currentScript.src.indexOf("http:")?"http:":"https:";var a=B.getMeasurementsScriptUrl(c);d(a)}catch(b){l|=256,f.report(f.ErrorTypes.InjectTagError,b.message,!0)}}},y="";try{y=window&&window.document&&window.document.currentScript&&window.document.currentScript.src}catch(c){}try{var A=
function(c){function a(a){var b={};a.split("&").forEach(function(a){a=a.trim().split("=");2===a.length&&(b[a[0].trim()]=a[1].trim())});return b}function b(a){var b={};["cmp","ctx","sid","plc"].forEach(function(c){a.hasOwnProperty(c)&&(b["dvp_"+c]=a[c])});return b}var d={},e={};(function(c){if(c){var g="";c=c.trim().split("?");2===c.length&&(g=c[1]);g&&(d=a(g),e=b(d))}})(c);return{toQueryString:function(a){var b="",c;for(c in a)a.hasOwnProperty(c)&&(b&&(b+="&"),b=[b,c,"=",a[c]].join(""));return b},
getQueryStringParams:function(){return d},getQueryStringClientParams:function(){return e}}}(y);var f=function(){function c(b,c,d){c=(c=c&&c&&c.trim().replace(/(\t|\n|\r|\|)/g,""))&&encodeURIComponent(c)||"";c=a.replace(/__ERR_MSG_PLACEHOLDR__/g,[b.message,c].join("__"));c=c.replace(/__CLIENT_ERROR_TYPE_PLACEHOLDR__/g,b.id);d&&(c+="&dvp_isLostImp=1");w.isSupported()&&(c+="&dvp_iomd=1");return c}var a="",b={ctx:818052,cmp:1619415,dvtagver:"6.1.src",tgjsver:"501",dvp_jsErrMsg:"__ERR_MSG_PLACEHOLDR__",
napr:"__ERR_MSG_PLACEHOLDR__",cerrt:"__CLIENT_ERROR_TYPE_PLACEHOLDR__"};p&&(b.dvp_idle=1);n&&(b.dvp_csp=1,b.dvp_csplog=l);a=["https://tps.doubleverify.com/visit.jpg?",[A.toQueryString(b),A.toQueryString(A.getQueryStringClientParams())].join("&")].join("");return{ErrorTypes:{OmidNativeCollectData:{id:512,message:"OmidNativeCollectData"},InjectTagError:{id:1,message:"InjectTagError"},LoadTagError:{id:2,message:"LoadTagError"},UnexpectedLostImpError:{id:4,message:"UnexpectedLostImpError"},OmidSessionError:{id:8,
message:"OmidSessionError"},OmidUnexpectedLostImpError:{id:16,message:"OmidUnexpectedLostImpError"},OmidLoadTagError:{id:32,message:"OmidLoadTagError"},OmidInjectTagError:{id:64,message:"OmidInjectTagError "},UnexpectedError:{id:128,message:"UnexpectedError"},OmidUnexpectedError:{id:256,message:"OmidUnexpectedError"}},report:function(a,b,d){k(c(a,b,d))},getReportUrl:c}}()}catch(c){F(c,128,0)}try{$dv="undefined"!=typeof $dv&&$dv||{tags:{},tagsCounter:0},$dv.tagsCounter++,$dv.tagData||($dv.tagData=
{}),$dv.tagData[h]={},$dv.tagData[h].dvtpScriptVersion="501",$dv.tagData[h].dvtpScriptUrl=y,$dv.tagData[h].cspIndicatorLogger=l,$dv.tagData[h].restrictedAccess=n,(w.isSupported()?w:m).execute()}catch(c){f?f.report(f.ErrorTypes.UnexpectedLostImpError,c.message,!0):F(c,4,1)}})();
