# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_hello.ipynb"}

modules = ["hello.py"]

doc_url = "https://seanczak.github.io/ts_blog/"

git_url = "https://github.com/seanczak/ts_blog/tree/master/"

def custom_doc_links(name): return None
